version: '3.9'
services:
  blog_postgresql:
    image: postgres:14.4-bullseye
    container_name: blog_postgresql
    ports:
      - "5432:5432"
    networks:
      - blog_net
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      APP_DB_USER: postgres
      APP_DB_PASS: 7daNLd@om8N4
      APP_DB_NAME: blog

  blog_service:
    build:
      context: .
      dockerfile: './docker/blog-service/Dockerfile'
    container_name: blog_service
    depends_on:
      - blog_postgresql
    ports:
      - "30303:2345"
      - "80:8080"
    networks:
      - blog_net
    volumes:
      - ./blog-service:/go/blog-service
    command: ["/bin/sh", "/run.sh"]
    environment:
      BLOG_WORKDIR: /go/blog-service
      POSTGRES_HOST: blog_postgresql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: 7daNLd@om8N4
      POSTGRES_DB: blog
      POSTGRES_SSLMODE: disable

networks:
  blog_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.144.0/24
